name: my_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  wemapgl:
    path: ./WeMap-Flutter-SDK
  location: ^4.1.1
  firebase_auth: ^1.2.0
  firebase_core: 
  cloud_firestore: ^2.2.0
  google_sign_in:


dev_dependencies:
  flutter_test:
    sdk: flutter
  

flutter:
  uses-material-design: true

  assets:
    - assets/symbols/custom-icon.png
    - assets/symbols/origin.png
    - assets/symbols/destination.png
    - assets/symbols/2.0x/custom-icon.png
    - assets/symbols/2.0x/origin.png
    - assets/symbols/2.0x/destination.png
    - assets/symbols/3.0x/custom-icon.png
    - assets/symbols/3.0x/origin.png
    - assets/symbols/3.0x/destination.png
    - assets/geojson/ne_10m_ports.geojson
    - assets/geojson/line-samples.geojson
    - assets/geojson/polygon-samples.geojson
    
    - assets/images/logo.png
    - assets/images/mark-location.png